apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivematica-storage-service
  namespace: '#{namespace}#'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: archivematica-storage-service
      app.kubernetes.io/instance: '#{namespace}#'
      app.kubernetes.io/part-of: piqlconnect
      app.kubernetes.io/managed-by: azure-devops    
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        app.kubernetes.io/name: archivematica-storage-service
        app.kubernetes.io/instance: '#{namespace}#'
        app.kubernetes.io/version: "#{VERSION}#"    
        app.kubernetes.io/part-of: piqlconnect
        app.kubernetes.io/managed-by: azure-devops
    spec:
      containers:
        - image: '#{DOCKER_REGISTRY}#/archivematica-storage-service:#{VERSION}#'
          name: archivematica-storage-service
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: storage_service.settings.local
            - name: FORWARDED_ALLOW_IPS
              value: '*'        
            - name: SS_DB_URL
              value: '#{SS_DB_URL}#'
            - name: SS_GNUPG_HOME_PATH
              value: /var/archivematica/storage_service/.gnupg
            - name: SS_GUNICORN_ACCESSLOG
              value: /dev/null
            - name: SS_GUNICORN_RELOAD
              value: "true"
            - name: SS_GUNICORN_RELOAD_ENGINE
              value: auto
          
          resources: 
            requests:
              memory: "256Mi"
              cpu: "1m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/archivematica/sharedDirectory
              name: archivematica-pipeline-data
            - mountPath: /var/archivematica/storage_service
              name: archivematica-storage-service-staging-data
            - mountPath: /home
              name: archivematica-storage-service-location-data

      initContainers:
        - name: archivematica-storage-service-loader
          image: '#{DOCKER_REGISTRY}#/archivematica-storage-service:#{VERSION}#'         
          command: ['/src/storage_service/manage.py']
          args: ["migrate help"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: storage_service.settings.local
            - name: FORWARDED_ALLOW_IPS
              value: '*'        
            - name: SS_DB_URL
              value: '#{SS_DB_URL}#'
            - name: SS_GNUPG_HOME_PATH
              value: /var/archivematica/storage_service/.gnupg
            - name: SS_GUNICORN_ACCESSLOG
              value: /dev/null
            - name: SS_GUNICORN_RELOAD
              value: "true"
            - name: SS_GUNICORN_RELOAD_ENGINE
              value: auto

      restartPolicy: Always

      volumes:       
        - name: archivematica-pipeline-data
          persistentVolumeClaim:
            claimName: archivematica-pipeline-data
        - name: archivematica-storage-service-staging-data
          persistentVolumeClaim:
            claimName: archivematica-storage-service-staging-data
        - name: archivematica-storage-service-location-data
          persistentVolumeClaim:
            claimName: archivematica-storage-service-location-data
