apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivematica-mcp-client
  namespace: '#{namespace}#' 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: archivematica-mcp-client
      app.kubernetes.io/instance: '#{namespace}#'
      app.kubernetes.io/part-of: piqlconnect
      app.kubernetes.io/managed-by: azure-devops 
  strategy:
    type: Recreate
  template:
    metadata:   
      labels:
        app.kubernetes.io/name: archivematica-mcp-client
        app.kubernetes.io/instance: '#{namespace}#'
        app.kubernetes.io/version: "#{VERSION}#"    
        app.kubernetes.io/part-of: piqlconnect
        app.kubernetes.io/managed-by: azure-devops
    spec:
      containers:
        - image: '#{DOCKER_REGISTRY}#/archivematica-mcp-client:#{VERSION}#'
          name: archivematica-mcp-client
          env:
            - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE
              value: MCP
            - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST
              value: mysql
            - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD
              value: demo
            - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_USER
              value: archivematica
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT
              value: "true"
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND
              value: clamdscanner
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_FILE_SIZE
              value: "2048"
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_SCAN_SIZE
              value: "2048"
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_MAX_STREAM_LENGTH
              value: "2048"
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER
              value: clamavd:3310
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER
              value: elasticsearch:9200
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER
              value: gearmand:4730
            - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED
              value: "false"
            - name: DJANGO_SECRET_KEY
              value: "12345"
            - name: DJANGO_SETTINGS_MODULE
              value: settings.common
            - name: NAILGUN_PORT
              value: "2113"
            - name: NAILGUN_SERVER
              value: fits
       
          resources: 
            requests:
              memory: "256Mi"
              cpu: "1m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/archivematica/sharedDirectory
              name: archivematica-pipeline-data
      restartPolicy: Always
      volumes:     
        - name: archivematica-pipeline-data
          persistentVolumeClaim:
            claimName: archivematica-pipeline-data
---
apiVersion: v1
kind: Service
metadata:
  app.kubernetes.io/name: archivematica-storage-service
spec:  
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: archivematica-storage-service