kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: archivematica-sc
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  skuName: Standard_LRS
  location: westeurope
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: archivematica-sc-premium
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  skuName: Premium_LRS
  location: westeurope