kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: archivematica-sc-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - uid=333
  - gid=333
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock
parameters:
  protocol: nfs
  skuName: Standard_LRS
  location: westeurope
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: archivematica-sc-premium-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - uid=333
  - gid=333
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock
parameters:
  protocol: nfs
  skuName: Premium_LRS
  location: westeurope
