apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '#{namespace}#-pipeline-data-claim'
  namespace: '#{namespace}#'
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '#{namespace}#-staging-data-claim'
  namespace: '#{namespace}#'
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '#{namespace}#-location-data-claim'
  namespace: '#{namespace}#'
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-premium
  resources:
    requests:
      storage: 100Gi

